[package]
name = "stork"
version = "0.1.0"
authors = ["James Little <littleguy23@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10.2"
serde_json = "1.0"
console_error_panic_hook = "0.1.6"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]