# The main Federalist index configuration file. This produces the Federalist
# search index seen on the home page of stork-search.net.
[input]
base_directory = "local-dev/test-corpora/simple"
files = [{ path = "simple.srt", url = "/", title = "Simple" }]
